spring:
  application:
    # name of the application
    name: spring-config-server
    # available profiles of the application
  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          # git url where the configurations are stored
          uri: https://github.com/filipve1994/spring-microservices-docker-starter-config-server
          # if configurations are in sub folders search the subfolder by below name
          search-paths: server-config/
server:
  # config server port
  port: 8888
management:
  security:
    # disable security of the config server
    enabled: false