server:
  port: 8200

spring:
  application:
    name: image-service

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

eureka:
  instance:
    appname: image-service
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/